const SCHOOLS_STORE = "SAVED-SCHOOLS"
const DEGREES_STORE = "SAVED-DEGREES"
const FIELD_STORE = "SAVED-FIELDS"

const TITLES_STORE = "SAVED-TITLES"
const COMPANIES_STORE = "SAVED-COMPANIES"
const INDUSTRIES_STORE = "SAVED-INDUSTRIES"

const LANGUAGES_STORE = "SAVED-LANGUAGES"

const SKILLS_STORE = "SAVED-SKILLS"

const CERTIFICATIONS_STORE = "SAVED-CERTIFICATIONS"

export {
    SCHOOLS_STORE,
    DEGREES_STORE,
    FIELD_STORE,
    TITLES_STORE,
    COMPANIES_STORE,
    INDUSTRIES_STORE,
    LANGUAGES_STORE,
    SKILLS_STORE,
    CERTIFICATIONS_STORE
}