const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
const REMOTE_HOST_NAME = process.env.REACT_APP_BASE_URL;
const UPLOADS_URL = process.env.REACT_APP_UPLOADS_URL;
const FRONTEND_URL = process.env.REACT_APP_FRONTEND_URL;
const CHAT_URL = process.env.REACT_APP_CHAT_URL;

const APP_ENV = {
    GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
    REMOTE_HOST_NAME: REMOTE_HOST_NAME,
    UPLOADS_URL: UPLOADS_URL,
    FRONTEND_URL: FRONTEND_URL,
    CHAT_URL: CHAT_URL
};

export { APP_ENV };