const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
const REMOTE_HOST_NAME = process.env.REACT_APP_BASE_URL;

const APP_ENV = {
    GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
    REMOTE_HOST_NAME: REMOTE_HOST_NAME
};

export { APP_ENV };