name: 🚀 Deploy website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
       - name: 🚚 Get latest code
         uses: actions/checkout@v2

      - name: Use Node.js 22.0.0
        uses: actions/setup-node@v2
        with:
          node-version: 22.0.0

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
        env:
          REACT_APP_GOOGLE_CLIENT_ID=498974476309-aqh8s3erdppj15kkjqdo5v9rb1plc4op.apps.googleusercontent.com
          REACT_APP_BASE_URL=https://api.kanenil.space/
          REACT_APP_FRONTEND_URL=https://kanenil.space
          REACT_APP_UPLOADS_URL=https://api.kanenil.space/uploads
          REACT_APP_CHAT_URL=https://api.kanenil.space/chat
          REACT_APP_CONNECTION_URL=https://api.kanenil.space/connection

      - name: List output files
        run: find build/ -print

      - name: 📂 Sync files
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp

          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}

          remote-path: /app

          remote-port: 221
