name: 🚀 Deploy website

on:
  push:
    branches: [main]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Use Node.js 22.0.0
        uses: actions/setup-node@v2
        with:
          node-version: 22.0.0

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
        env:
          REACT_APP_GOOGLE_CLIENT_ID: 475188833630-edsejj98apbd752mmjisb7j5o7klu1mf.apps.googleusercontent.com
          REACT_APP_BASE_URL: https://api.kanenil.space/
          REACT_APP_FRONTEND_URL: https://kanenil.space
          REACT_APP_UPLOADS_URL: https://api.kanenil.space/uploads
          REACT_APP_CHAT_URL: https://api.kanenil.space/chat
          REACT_APP_CONNECTION_URL: https://api.kanenil.space/connection
          CI: false

      - name: List output files
        run: find build/ -print

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          protocol: ftp
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /app/
